version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: nestjs_backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    restart: always